CREATE SEQUENCE IF NOT EXISTS D_SEQUENCE START 1;

CREATE TABLE IF NOT EXISTS D_COFFEE (
  ID VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SYS_USER (
  ID BIGINT NOT NULL,
  USER_NAME VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ENABLED INT NOT NULL DEFAULT 1,
  REC_STATUS CHAR(1) NOT NULL,
  LAST_LOGIN TIMESTAMP NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS D_AIRCRAFT (
ID BIGINT NOT NULL PRIMARY KEY,
CALLSIGN VARCHAR(7),
SQUAWK VARCHAR(4),
REG VARCHAR(6),
FLIGHTNO VARCHAR(10),
ROUTE VARCHAR(25),
TYPE VARCHAR(4),
CATEGORY VARCHAR(2),
ALTITUDE INT,
HEADING INT,
SPEED INT,
VERT_RATE INT,
SELECTED_ALTITUDE INT,
LAT NUMERIC(20, 4),
LON NUMERIC(20, 4),
BAROMETER NUMERIC(20, 4),
POLAR_DISTANCE NUMERIC(20, 4),
POLAR_BEARING NUMERIC(20, 4),
ISADSB BOOLEAN,
IS_ON_GROUND BOOLEAN,
LAST_SEEN_TIME TIMESTAMP,
POS_UPDATE_TIME TIMESTAMP,
BDS40SEEN_TIME TIMESTAMP);