CREATE TABLE TG_ACTIVE_CHAT (
 ID BIGINT PRIMARY KEY NOT NULL,
 CHAT_ID BIGINT NOT NULL
);

CREATE TABLE TG_INCOME (
 ID BIGINT PRIMARY KEY NOT NULL,
 CHAT_ID BIGINT NOT NULL,
 INCOME NUMERIC(25, 7) NULL
);

CREATE TABLE TG_SPEND (
 ID BIGINT PRIMARY KEY NOT NULL,
 CHAT_ID BIGINT NOT NULL,
 SPEND NUMERIC(25, 7) NULL
);

CREATE SEQUENCE TG_SEQUENCE
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;