CREATE SEQUENCE IF NOT EXISTS D_SEQUENCE START 1;

CREATE TABLE IF NOT EXISTS SYS_USER (
  ID BIGINT NOT NULL,
  USER_NAME VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,  
  EMAIL VARCHAR(100) NOT NULL,
  ENABLED INT not null default 1,
  REC_STATUS CHAR(1) NOT NULL,
  LAST_LOGIN TIMESTAMP NULL,
  PRIMARY KEY (ID)
);
